project_id = "yqizlfwylffbdcykkqzx"

[functions.parse-efd-icms]
verify_jwt = false

[functions.process-efd-icms-job]
verify_jwt = false

[functions.verify-security-keyword]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.clear-company-data]
verify_jwt = false

[functions.list-tenants]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false
