project_id = "kocbdudzkbvgxwdacdrk"

[functions.onboarding-complete]
verify_jwt = false

[functions.parse-efd]
verify_jwt = false

[functions.process-efd-job]
verify_jwt = false

[functions.send-import-email]
verify_jwt = false

[functions.cancel-import-job]
verify_jwt = false

[functions.clear-imported-data]
verify_jwt = false

[functions.join-tenant]
verify_jwt = false

[functions.get-tenant-structure]
verify_jwt = false

[functions.reset-all-data]
verify_jwt = false
